// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://strcwwulrqlmugtcfrkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0cmN3d3VscnFsbXVndGNmcmtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMzA3NzAsImV4cCI6MjA1OTkwNjc3MH0.oJ5Tb6IsLxNfEHC_EZUkiM748SwV9_wK-kweVBcsZIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);